backend:
  name: github
  repo: desirlukenson00-cyber/pead-website
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Paj Sit la"
    files:
      - label: "Akey"
        name: "index"
        file: "content/index.md"
        fields:
          - { label: "Tit", name: "title", widget: "string" }
          - { label: "Deskripsyon", name: "description", widget: "text" }
